
import express from 'express';
import Product from '../models/Product.js';

const router = express.Router();


const mockProducts = [
  {
    id: 1,
    name: "iPhone 15 Pro ",
    category: "Electronics",
    subcategory: "Smartphones",
    price: 1199.99,
    originalPrice: 1299.99,
    discount: 8,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400",
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400",
    ],
    description:
      "The most advanced iPhone yet with titanium design, A17 Pro chip, and revolutionary camera system.",
    brand: "Apple",
    rating: 4.8,
    reviews: 2847,
    inStock: true,
    stock: 15,
    sku: "APL-IP15PM-256",
    weight: "221g",
    dimensions: "159.9 x 76.7 x 8.25 mm",
    color: "Natural Titanium",
    colors: [
      "Natural Titanium",
      "Blue Titanium",
      "White Titanium",
      "Black Titanium",
    ],
    storage: "256GB",
    storageOptions: ["128GB", "256GB", "512GB", "1TB"],
    tags: ["premium", "5G", "wireless-charging", "water-resistant"],
    shipping: {
      free: true,
      estimatedDays: "2-3",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra",
    category: "Electronics",
    subcategory: "Smartphones",
    price: 1099.99,
    originalPrice: 1199.99,
    discount: 8,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400",
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400",
      "https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=400",
    ],
    description:
      "Ultimate productivity powerhouse with S Pen, 200MP camera, and AI-powered features.",
    brand: "Samsung",
    rating: 4.7,
    reviews: 1923,
    inStock: true,
    stock: 23,
    sku: "SAM-GS24U-512",
    weight: "233g",
    dimensions: "162.3 x 79.0 x 8.6 mm",
    color: "Titanium Black",
    colors: [
      "Titanium Black",
      "Titanium Gray",
      "Titanium Violet",
      "Titanium Yellow",
    ],
    storage: "512GB",
    storageOptions: ["256GB", "512GB", "1TB"],
    tags: ["s-pen", "5G", "wireless-charging", "water-resistant"],
    shipping: {
      free: true,
      estimatedDays: "1-2",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },

  // Electronics - Laptops
  {
    id: 3,
    name: "MacBook Pro 16-inch M3 Pro",
    category: "Electronics",
    subcategory: "Laptops",
    price: 2499.99,
    originalPrice: 2699.99,
    discount: 7,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=400",
    ],
    description:
      "Professional laptop with M3 Pro chip, stunning Liquid Retina XDR display, and all-day battery life.",
    brand: "Apple",
    rating: 4.9,
    reviews: 1456,
    inStock: true,
    stock: 8,
    sku: "APL-MBP16-M3P",
    weight: "2.15kg",
    dimensions: "35.57 x 24.81 x 1.68 cm",
    color: "Space Gray",
    colors: ["Space Gray", "Silver"],
    storage: "512GB SSD",
    storageOptions: ["512GB SSD", "1TB SSD", "2TB SSD"],
    memory: "18GB",
    memoryOptions: ["18GB", "36GB"],
    processor: "Apple M3 Pro",
    display: "16-inch Liquid Retina XDR",
    tags: ["professional", "creative", "long-battery", "retina-display"],
    shipping: {
      free: true,
      estimatedDays: "3-5",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 4,
    name: "Dell XPS 13 Plus",
    category: "Electronics",
    subcategory: "Laptops",
    price: 1299.99,
    originalPrice: 1499.99,
    discount: 13,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400",
    images: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400",
    ],
    description:
      "Ultra-thin premium laptop with InfinityEdge display and cutting-edge performance.",
    brand: "Dell",
    rating: 4.6,
    reviews: 892,
    inStock: true,
    stock: 12,
    sku: "DELL-XPS13P-I7",
    weight: "1.24kg",
    dimensions: "29.56 x 19.92 x 1.36 cm",
    color: "Platinum Silver",
    colors: ["Platinum Silver", "Graphite"],
    storage: "512GB SSD",
    storageOptions: ["256GB SSD", "512GB SSD", "1TB SSD"],
    memory: "16GB",
    memoryOptions: ["8GB", "16GB", "32GB"],
    processor: "Intel Core i7-1360P",
    display: "13.4-inch OLED Touch",
    tags: ["ultrabook", "touchscreen", "lightweight", "business"],
    shipping: {
      free: true,
      estimatedDays: "2-4",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },

  // Fashion - Men's Clothing
  {
    id: 5,
    name: "Classic Denim Jacket",
    category: "Fashion",
    subcategory: "Men's Clothing",
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
    ],
    description:
      "Timeless denim jacket crafted from premium cotton with classic fit and authentic wash.",
    brand: "Levi's",
    rating: 4.5,
    reviews: 2341,
    inStock: true,
    stock: 45,
    sku: "LEV-DJ-CLASSIC",
    weight: "680g",
    color: "Medium Wash",
    colors: ["Light Wash", "Medium Wash", "Dark Wash", "Black"],
    size: "M",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    material: "100% Cotton",
    careInstructions: "Machine wash cold, tumble dry low",
    tags: ["casual", "classic", "denim", "versatile"],
    shipping: {
      free: false,
      estimatedDays: "5-7",
      cost: 9.99,
    },
    returnPolicy: "60 days",
    warranty: "6 months",
  },
  {
    id: 6,
    name: "Premium Cotton T-Shirt",
    category: "Fashion",
    subcategory: "Men's Clothing",
    price: 24.99,
    originalPrice: 34.99,
    discount: 29,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
      "https://images.unsplash.com/photo-1583743814966-8936f37f82e2?w=400",
    ],
    description:
      "Soft, comfortable premium cotton t-shirt with perfect fit and lasting quality.",
    brand: "Everlane",
    rating: 4.7,
    reviews: 3892,
    inStock: true,
    stock: 156,
    sku: "EVR-CT-PREM",
    weight: "180g",
    color: "Navy",
    colors: ["White", "Black", "Navy", "Gray", "Olive", "Burgundy"],
    size: "L",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    material: "100% Organic Cotton",
    careInstructions: "Machine wash warm, tumble dry medium",
    tags: ["basic", "organic", "comfortable", "everyday"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 5.99,
    },
    returnPolicy: "30 days",
    warranty: "3 months",
  },

  // Fashion - Women's Clothing
  {
    id: 7,
    name: "Floral Summer Dress",
    category: "Fashion",
    subcategory: "Women's Clothing",
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
    images: [
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400",
      "https://images.unsplash.com/photo-1566479179817-0b9f8eb9b0ab?w=400",
    ],
    description:
      "Elegant floral dress perfect for summer occasions with flowing silhouette and breathable fabric.",
    brand: "Zara",
    rating: 4.4,
    reviews: 1567,
    inStock: true,
    stock: 34,
    sku: "ZAR-FD-SUM",
    weight: "320g",
    color: "Floral Blue",
    colors: ["Floral Blue", "Floral Pink", "Floral Yellow", "Solid Black"],
    size: "M",
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "95% Polyester, 5% Elastane",
    careInstructions: "Hand wash cold, hang dry",
    tags: ["summer", "floral", "elegant", "breathable"],
    shipping: {
      free: false,
      estimatedDays: "4-6",
      cost: 7.99,
    },
    returnPolicy: "30 days",
    warranty: "3 months",
  },
  {
    id: 8,
    name: "High-Waisted Skinny Jeans",
    category: "Fashion",
    subcategory: "Women's Clothing",
    price: 69.99,
    originalPrice: 89.99,
    discount: 22,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400",
    images: [
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400",
      "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400",
    ],
    description:
      "Flattering high-waisted skinny jeans with stretch comfort and classic styling.",
    brand: "American Eagle",
    rating: 4.6,
    reviews: 2876,
    inStock: true,
    stock: 67,
    sku: "AE-HW-SKINNY",
    weight: "450g",
    color: "Dark Wash",
    colors: ["Light Wash", "Medium Wash", "Dark Wash", "Black", "White"],
    size: "28",
    sizes: ["24", "26", "28", "30", "32", "34"],
    material: "76% Cotton, 22% Polyester, 2% Elastane",
    careInstructions: "Machine wash cold, tumble dry low",
    tags: ["skinny", "high-waisted", "stretch", "versatile"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 6.99,
    },
    returnPolicy: "60 days",
    warranty: "6 months",
  },

  // Home & Garden - Furniture
  {
    id: 9,
    name: "Modern Ergonomic Office Chair",
    category: "Home & Garden",
    subcategory: "Furniture",
    price: 299.99,
    originalPrice: 399.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
      "https://images.unsplash.com/photo-1541558869434-2840d308329a?w=400",
    ],
    description:
      "Ergonomic office chair with lumbar support, adjustable height, and breathable mesh back.",
    brand: "Steelcase",
    rating: 4.8,
    reviews: 1234,
    inStock: true,
    stock: 18,
    sku: "STC-EOC-MOD",
    weight: "18kg",
    dimensions: "68 x 68 x 107-117 cm",
    color: "Black",
    colors: ["Black", "Gray", "White", "Blue"],
    material: "Mesh, Steel, Plastic",
    assembly: "Required",
    tags: ["ergonomic", "office", "adjustable", "breathable"],
    shipping: {
      free: true,
      estimatedDays: "5-7",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "5 years",
  },
  {
    id: 10,
    name: "Scandinavian Coffee Table",
    category: "Home & Garden",
    subcategory: "Furniture",
    price: 189.99,
    originalPrice: 249.99,
    discount: 24,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
      "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=400",
    ],
    description:
      "Minimalist Scandinavian-style coffee table crafted from sustainable oak wood.",
    brand: "IKEA",
    rating: 4.5,
    reviews: 892,
    inStock: true,
    stock: 25,
    sku: "IKEA-SCT-OAK",
    weight: "15kg",
    dimensions: "118 x 78 x 45 cm",
    color: "Natural Oak",
    colors: ["Natural Oak", "White Oak", "Walnut"],
    material: "Solid Oak Wood",
    assembly: "Required",
    tags: ["scandinavian", "minimalist", "wooden", "living-room"],
    shipping: {
      free: false,
      estimatedDays: "7-10",
      cost: 29.99,
    },
    returnPolicy: "90 days",
    warranty: "2 years",
  },

  // Sports & Outdoors
  {
    id: 11,
    name: "Professional Yoga Mat",
    category: "Sports & Outdoors",
    subcategory: "Fitness",
    price: 49.99,
    originalPrice: 69.99,
    discount: 29,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    images: [
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    ],
    description:
      "Premium non-slip yoga mat with superior grip and cushioning for all yoga practices.",
    brand: "Manduka",
    rating: 4.7,
    reviews: 2156,
    inStock: true,
    stock: 89,
    sku: "MAN-YM-PRO",
    weight: "2.5kg",
    dimensions: "185 x 66 x 0.6 cm",
    color: "Purple",
    colors: ["Purple", "Blue", "Green", "Black", "Pink"],
    material: "Natural Rubber",
    thickness: "6mm",
    tags: ["yoga", "non-slip", "eco-friendly", "professional"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 8.99,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 12,
    name: "Hiking Backpack 40L",
    category: "Sports & Outdoors",
    subcategory: "Outdoor Gear",
    price: 129.99,
    originalPrice: 179.99,
    discount: 28,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
      "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400",
    ],
    description:
      "Durable 40L hiking backpack with multiple compartments and weather-resistant design.",
    brand: "Osprey",
    rating: 4.8,
    reviews: 967,
    inStock: true,
    stock: 32,
    sku: "OSP-HB-40L",
    weight: "1.8kg",
    dimensions: "60 x 30 x 25 cm",
    color: "Forest Green",
    colors: ["Forest Green", "Mountain Blue", "Desert Orange", "Charcoal"],
    material: "Ripstop Nylon",
    capacity: "40L",
    features: ["Rain Cover", "Hydration Compatible", "Multiple Pockets"],
    tags: ["hiking", "outdoor", "waterproof", "durable"],
    shipping: {
      free: true,
      estimatedDays: "4-6",
      cost: 0,
    },
    returnPolicy: "60 days",
    warranty: "2 years",
  },

  // Beauty & Personal Care
  {
    id: 13,
    name: "Vitamin C Serum",
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400",
    images: [
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400",
      "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400",
    ],
    description:
      "Brightening vitamin C serum with antioxidants for radiant, youthful-looking skin.",
    brand: "The Ordinary",
    rating: 4.6,
    reviews: 3456,
    inStock: true,
    stock: 124,
    sku: "TO-VCS-30ML",
    weight: "50g",
    volume: "30ml",
    ingredients: "Ascorbic Acid, Hyaluronic Acid, Vitamin E",
    skinType: "All Skin Types",
    tags: ["vitamin-c", "brightening", "anti-aging", "serum"],
    shipping: {
      free: false,
      estimatedDays: "2-4",
      cost: 4.99,
    },
    returnPolicy: "30 days",
    warranty: "6 months",
  },
  {
    id: 14,
    name: "Wireless Hair Straightener",
    category: "Beauty & Personal Care",
    subcategory: "Hair Care",
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400",
    images: [
      "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400",
      "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400",
    ],
    description:
      "Cordless hair straightener with ceramic plates and adjustable temperature settings.",
    brand: "Dyson",
    rating: 4.4,
    reviews: 876,
    inStock: true,
    stock: 45,
    sku: "DYS-WHS-CER",
    weight: "420g",
    dimensions: "25 x 3 x 4 cm",
    color: "Rose Gold",
    colors: ["Rose Gold", "Black", "White"],
    material: "Ceramic Plates",
    temperature: "120°C - 210°C",
    batteryLife: "30 minutes",
    tags: ["wireless", "ceramic", "travel", "professional"],
    shipping: {
      free: true,
      estimatedDays: "2-3",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "2 years",
  },

  // Books & Media
  {
    id: 15,
    name: "Atomic Habits",
    category: "Books & Media",
    subcategory: "Self-Help",
    price: 14.99,
    originalPrice: 18.99,
    discount: 21,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
    images: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    ],
    description:
      "An Easy & Proven Way to Build Good Habits & Break Bad Ones by James Clear.",
    brand: "Avery",
    author: "James Clear",
    rating: 4.9,
    reviews: 15678,
    inStock: true,
    stock: 234,
    sku: "AVR-AH-JC",
    weight: "340g",
    pages: 320,
    language: "English",
    format: "Paperback",
    isbn: "978-0735211292",
    publishedDate: "2018-10-16",
    tags: ["self-help", "habits", "productivity", "bestseller"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 3.99,
    },
    returnPolicy: "30 days",
    warranty: "N/A",
  },

  // Food & Beverages
  {
    id: 16,
    name: "Organic Cold Brew Coffee",
    category: "Food & Beverages",
    subcategory: "Coffee",
    price: 12.99,
    originalPrice: 15.99,
    discount: 19,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400",
    images: [
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400",
    ],
    description:
      "Smooth, rich organic cold brew coffee concentrate. Just add water or milk.",
    brand: "Blue Bottle",
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    stock: 67,
    sku: "BB-CB-ORG",
    weight: "946ml",
    volume: "32 fl oz",
    ingredients: "Organic Coffee, Water",
    caffeine: "High",
    origin: "Single Origin Ethiopia",
    expiryDate: "2025-12-31",
    tags: ["organic", "cold-brew", "concentrate", "single-origin"],
    shipping: {
      free: false,
      estimatedDays: "2-4",
      cost: 6.99,
    },
    returnPolicy: "14 days",
    warranty: "N/A",
  },

  // Pet Supplies
  {
    id: 17,
    name: "Interactive Dog Puzzle Toy",
    category: "Pet Supplies",
    subcategory: "Dog Toys",
    price: 19.99,
    originalPrice: 29.99,
    discount: 33,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400",
    ],
    description:
      "Mental stimulation puzzle toy to keep dogs engaged and reduce boredom.",
    brand: "KONG",
    rating: 4.7,
    reviews: 2345,
    inStock: true,
    stock: 89,
    sku: "KONG-PUZ-INT",
    weight: "450g",
    dimensions: "25 x 25 x 5 cm",
    color: "Blue",
    colors: ["Blue", "Red", "Green", "Orange"],
    material: "Non-toxic Plastic",
    petSize: "Medium",
    petSizes: ["Small", "Medium", "Large"],
    tags: ["interactive", "puzzle", "mental-stimulation", "durable"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 5.99,
    },
    returnPolicy: "30 days",
    warranty: "6 months",
  },

  // Additional products to reach 100+
  {
    id: 18,
    name: "Wireless Bluetooth Headphones",
    category: "Electronics",
    subcategory: "Audio",
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400",
    ],
    description:
      "Premium noise-canceling wireless headphones with 30-hour battery life.",
    brand: "Sony",
    rating: 4.8,
    reviews: 3421,
    inStock: true,
    stock: 34,
    sku: "SONY-WH-1000XM5",
    weight: "250g",
    color: "Black",
    colors: ["Black", "Silver", "Blue", "Midnight Blue"],
    batteryLife: "30 hours",
    connectivity: "Bluetooth 5.2",
    features: ["Noise Canceling", "Quick Charge", "Voice Assistant"],
    tags: ["wireless", "noise-canceling", "premium", "long-battery"],
    shipping: {
      free: true,
      estimatedDays: "1-2",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 19,
    name: "Smart Watch Series 9",
    category: "Electronics",
    subcategory: "Wearables",
    price: 399.99,
    originalPrice: 449.99,
    discount: 11,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400",
    images: [
      "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400",
      "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400",
    ],
    description:
      "Advanced smartwatch with health monitoring, GPS, and cellular connectivity.",
    brand: "Apple",
    rating: 4.7,
    reviews: 5678,
    inStock: true,
    stock: 28,
    sku: "APL-SW-S9",
    weight: "38.7g",
    dimensions: "45 x 38 x 10.7 mm",
    color: "Midnight",
    colors: ["Midnight", "Starlight", "Silver", "Product Red"],
    size: "45mm",
    sizes: ["41mm", "45mm"],
    batteryLife: "18 hours",
    features: ["GPS", "Cellular", "Health Monitoring", "Water Resistant"],
    tags: ["smartwatch", "fitness", "gps", "cellular"],
    shipping: {
      free: true,
      estimatedDays: "1-3",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 20,
    name: "Gaming Mechanical Keyboard",
    category: "Electronics",
    subcategory: "Gaming",
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400",
    images: [
      "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400",
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400",
    ],
    description:
      "RGB mechanical gaming keyboard with Cherry MX switches and customizable lighting.",
    brand: "Razer",
    rating: 4.6,
    reviews: 2134,
    inStock: true,
    stock: 56,
    sku: "RZR-MK-RGB",
    weight: "1.2kg",
    dimensions: "44 x 15.4 x 3.6 cm",
    color: "Black",
    colors: ["Black", "White"],
    switchType: "Cherry MX Blue",
    switchOptions: ["Cherry MX Blue", "Cherry MX Red", "Cherry MX Brown"],
    lighting: "RGB",
    connectivity: "USB-C",
    tags: ["gaming", "mechanical", "rgb", "customizable"],
    shipping: {
      free: true,
      estimatedDays: "2-4",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "2 years",
  },
  {
    id: 21,
    name: "Casual Sneakers",
    category: "Fashion",
    subcategory: "Footwear",
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400",
    images: [
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400",
      "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400",
    ],
    description:
      "Comfortable casual sneakers perfect for everyday wear with breathable design.",
    brand: "Adidas",
    rating: 4.5,
    reviews: 3421,
    inStock: true,
    stock: 89,
    sku: "ADI-CS-WHT",
    weight: "320g",
    color: "White",
    colors: ["White", "Black", "Gray", "Navy", "Red"],
    size: "9",
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "12",
    ],
    material: "Synthetic Leather, Mesh",
    sole: "Rubber",
    tags: ["casual", "comfortable", "breathable", "everyday"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 8.99,
    },
    returnPolicy: "60 days",
    warranty: "6 months",
  },
  {
    id: 22,
    name: "Leather Handbag",
    category: "Fashion",
    subcategory: "Accessories",
    price: 159.99,
    originalPrice: 219.99,
    discount: 27,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
      "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=400",
    ],
    description:
      "Elegant genuine leather handbag with multiple compartments and adjustable strap.",
    brand: "Michael Kors",
    rating: 4.7,
    reviews: 1876,
    inStock: true,
    stock: 23,
    sku: "MK-LH-TAN",
    weight: "680g",
    dimensions: "32 x 25 x 12 cm",
    color: "Tan",
    colors: ["Black", "Brown", "Tan", "Navy", "Burgundy"],
    material: "Genuine Leather",
    features: ["Multiple Compartments", "Adjustable Strap", "Magnetic Closure"],
    tags: ["leather", "elegant", "handbag", "accessories"],
    shipping: {
      free: true,
      estimatedDays: "3-5",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 23,
    name: "Silk Scarf",
    category: "Fashion",
    subcategory: "Accessories",
    price: 45.99,
    originalPrice: 65.99,
    discount: 30,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1601656195355-dd8923a3d388?w=400",
    images: [
      "https://images.unsplash.com/photo-1601656195355-dd8923a3d388?w=400",
      "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400",
    ],
    description:
      "Luxurious silk scarf with beautiful floral pattern, perfect for any season.",
    brand: "Hermès",
    rating: 4.8,
    reviews: 567,
    inStock: true,
    stock: 45,
    sku: "HER-SS-FLOR",
    weight: "45g",
    dimensions: "90 x 90 cm",
    color: "Floral Multi",
    colors: ["Floral Multi", "Geometric Blue", "Abstract Red", "Classic Black"],
    material: "100% Silk",
    careInstructions: "Dry clean only",
    tags: ["silk", "luxury", "scarf", "floral"],
    shipping: {
      free: false,
      estimatedDays: "4-6",
      cost: 9.99,
    },
    returnPolicy: "30 days",
    warranty: "6 months",
  },
  {
    id: 24,
    name: "Dining Table Set",
    category: "Home & Garden",
    subcategory: "Furniture",
    price: 599.99,
    originalPrice: 799.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1549497538-303791108f95?w=400",
    images: [
      "https://images.unsplash.com/photo-1549497538-303791108f95?w=400",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
    ],
    description:
      "Modern 6-seater dining table set with comfortable chairs and elegant design.",
    brand: "West Elm",
    rating: 4.6,
    reviews: 234,
    inStock: true,
    stock: 8,
    sku: "WE-DTS-6",
    weight: "45kg",
    dimensions: "180 x 90 x 75 cm",
    color: "Natural Wood",
    colors: ["Natural Wood", "Dark Walnut", "White Oak"],
    material: "Solid Wood, Fabric",
    seating: "6 people",
    assembly: "Required",
    tags: ["dining", "furniture", "modern", "6-seater"],
    shipping: {
      free: true,
      estimatedDays: "7-14",
      cost: 0,
    },
    returnPolicy: "60 days",
    warranty: "2 years",
  },
  {
    id: 25,
    name: "LED Desk Lamp",
    category: "Home & Garden",
    subcategory: "Lighting",
    price: 39.99,
    originalPrice: 59.99,
    discount: 33,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    images: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    ],
    description:
      "Adjustable LED desk lamp with touch controls and USB charging port.",
    brand: "Philips",
    rating: 4.5,
    reviews: 1234,
    inStock: true,
    stock: 67,
    sku: "PHI-LED-DESK",
    weight: "1.2kg",
    dimensions: "45 x 20 x 15 cm",
    color: "White",
    colors: ["White", "Black", "Silver"],
    brightness: "Adjustable (3 levels)",
    features: ["Touch Control", "USB Charging", "Adjustable Arm"],
    powerSource: "AC Adapter",
    tags: ["led", "adjustable", "desk-lamp", "usb-charging"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 7.99,
    },
    returnPolicy: "30 days",
    warranty: "2 years",
  },
  {
    id: 26,
    name: "Essential Oil Diffuser",
    category: "Home & Garden",
    subcategory: "Home Decor",
    price: 49.99,
    originalPrice: 69.99,
    discount: 29,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    images: [
      "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
      "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    ],
    description:
      "Ultrasonic essential oil diffuser with LED lights and timer settings.",
    brand: "URPOWER",
    rating: 4.4,
    reviews: 2567,
    inStock: true,
    stock: 123,
    sku: "URP-EOD-ULT",
    weight: "680g",
    dimensions: "16.8 x 12.2 x 16.8 cm",
    color: "Wood Grain",
    colors: ["Wood Grain", "White", "Dark Wood"],
    capacity: "300ml",
    runtime: "6-10 hours",
    features: ["LED Lights", "Timer", "Auto Shut-off"],
    tags: ["aromatherapy", "diffuser", "led-lights", "timer"],
    shipping: {
      free: false,
      estimatedDays: "4-6",
      cost: 6.99,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 27,
    name: "Running Shoes",
    category: "Sports & Outdoors",
    subcategory: "Athletic Footwear",
    price: 119.99,
    originalPrice: 159.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400",
    ],
    description:
      "High-performance running shoes with responsive cushioning and breathable mesh.",
    brand: "Nike",
    rating: 4.7,
    reviews: 4523,
    inStock: true,
    stock: 78,
    sku: "NIKE-RS-AIR",
    weight: "280g",
    color: "Black/White",
    colors: ["Black/White", "Blue/Gray", "Red/Black", "All Black"],
    size: "9",
    sizes: [
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "12",
    ],
    material: "Mesh, Synthetic",
    sole: "Air Cushion",
    features: ["Air Cushioning", "Breathable Mesh", "Lightweight"],
    tags: ["running", "athletic", "cushioned", "breathable"],
    shipping: {
      free: true,
      estimatedDays: "2-4",
      cost: 0,
    },
    returnPolicy: "60 days",
    warranty: "6 months",
  },
  {
    id: 28,
    name: "Protein Powder",
    category: "Sports & Outdoors",
    subcategory: "Nutrition",
    price: 39.99,
    originalPrice: 49.99,
    discount: 20,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
      "https://images.unsplash.com/photo-1594737626072-90dc274bc2bd?w=400",
    ],
    description:
      "Premium whey protein powder with 25g protein per serving, chocolate flavor.",
    brand: "Optimum Nutrition",
    rating: 4.6,
    reviews: 6789,
    inStock: true,
    stock: 234,
    sku: "ON-PP-CHOC-2LB",
    weight: "2lbs (907g)",
    flavor: "Chocolate",
    flavors: ["Chocolate", "Vanilla", "Strawberry", "Cookies & Cream"],
    servings: "28 servings",
    proteinPerServing: "25g",
    ingredients: "Whey Protein Isolate, Natural Flavors, Stevia",
    tags: ["protein", "whey", "muscle-building", "post-workout"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 8.99,
    },
    returnPolicy: "30 days",
    warranty: "N/A",
  },
  {
    id: 29,
    name: "Moisturizing Face Cream",
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    price: 24.99,
    originalPrice: 34.99,
    discount: 29,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
      "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400",
    ],
    description:
      "Deeply hydrating face cream with hyaluronic acid and peptides for all skin types.",
    brand: "CeraVe",
    rating: 4.7,
    reviews: 5432,
    inStock: true,
    stock: 189,
    sku: "CVE-MFC-50ML",
    weight: "75g",
    volume: "50ml",
    ingredients: "Hyaluronic Acid, Ceramides, Peptides",
    skinType: "All Skin Types",
    spf: "None",
    tags: ["moisturizer", "hyaluronic-acid", "hydrating", "daily-use"],
    shipping: {
      free: false,
      estimatedDays: "2-4",
      cost: 4.99,
    },
    returnPolicy: "30 days",
    warranty: "6 months",
  },
  {
    id: 30,
    name: "Electric Toothbrush",
    category: "Beauty & Personal Care",
    subcategory: "Oral Care",
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400",
    images: [
      "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400",
      "https://images.unsplash.com/photo-1631815588090-6f95d41711f9?w=400",
    ],
    description:
      "Rechargeable electric toothbrush with multiple cleaning modes and pressure sensor.",
    brand: "Oral-B",
    rating: 4.8,
    reviews: 3456,
    inStock: true,
    stock: 67,
    sku: "OB-ET-PRO",
    weight: "134g",
    color: "White/Blue",
    colors: ["White/Blue", "Black", "Pink"],
    batteryLife: "14 days",
    modes: ["Daily Clean", "Gum Care", "Sensitive", "Whitening"],
    features: ["Pressure Sensor", "Timer", "Multiple Modes"],
    tags: ["electric", "rechargeable", "pressure-sensor", "oral-care"],
    shipping: {
      free: true,
      estimatedDays: "2-4",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "2 years",
  },
  {
    id: 31,
    name: "4K Smart TV 55-inch",
    category: "Electronics",
    subcategory: "Television",
    price: 799.99,
    originalPrice: 999.99,
    discount: 20,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400",
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400",
      "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=400",
    ],
    description:
      "55-inch 4K Ultra HD Smart TV with HDR, built-in streaming apps, and voice control.",
    brand: "Samsung",
    rating: 4.6,
    reviews: 2341,
    inStock: true,
    stock: 15,
    sku: "SAM-TV55-4K",
    weight: "18.5kg",
    dimensions: "123.1 x 70.7 x 5.9 cm",
    color: "Black",
    colors: ["Black"],
    screenSize: "55 inches",
    screenSizes: ["43", "50", "55", "65", "75"],
    resolution: "4K Ultra HD (3840x2160)",
    smartTV: true,
    hdr: "HDR10+",
    features: ["Voice Control", "Built-in Apps", "WiFi", "Bluetooth"],
    tags: ["4k", "smart-tv", "hdr", "streaming"],
    shipping: {
      free: true,
      estimatedDays: "5-7",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "2 years",
  },
  {
    id: 32,
    name: "Wireless Gaming Mouse",
    category: "Electronics",
    subcategory: "Gaming",
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=400",
    images: [
      "https://images.unsplash.com/photo-1527814050087-3793815479db?w=400",
      "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400",
    ],
    description:
      "High-precision wireless gaming mouse with RGB lighting and programmable buttons.",
    brand: "Logitech",
    rating: 4.7,
    reviews: 1876,
    inStock: true,
    stock: 89,
    sku: "LOG-WGM-RGB",
    weight: "99g",
    dimensions: "12.6 x 6.8 x 4.3 cm",
    color: "Black",
    colors: ["Black", "White"],
    dpi: "25,600 DPI",
    batteryLife: "250 hours",
    connectivity: "2.4GHz Wireless",
    features: ["RGB Lighting", "11 Programmable Buttons", "Hero Sensor"],
    tags: ["gaming", "wireless", "rgb", "programmable"],
    shipping: {
      free: true,
      estimatedDays: "2-3",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "2 years",
  },
  {
    id: 33,
    name: "Bluetooth Speaker",
    category: "Electronics",
    subcategory: "Audio",
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400",
    images: [
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400",
      "https://images.unsplash.com/photo-1589492477829-5e65395b66cc?w=400",
    ],
    description:
      "Portable Bluetooth speaker with 360-degree sound and 12-hour battery life.",
    brand: "JBL",
    rating: 4.5,
    reviews: 3456,
    inStock: true,
    stock: 156,
    sku: "JBL-BT-360",
    weight: "540g",
    dimensions: "19.5 x 6.9 x 6.9 cm",
    color: "Blue",
    colors: ["Blue", "Red", "Black", "Gray", "Green"],
    batteryLife: "12 hours",
    waterproof: "IPX7",
    connectivity: "Bluetooth 5.1",
    features: ["360-degree Sound", "Waterproof", "PartyBoost"],
    tags: ["bluetooth", "portable", "waterproof", "party"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 7.99,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 34,
    name: "Wireless Earbuds Pro",
    category: "Electronics",
    subcategory: "Audio",
    price: 179.99,
    originalPrice: 229.99,
    discount: 22,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400",
    images: [
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400",
      "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=400",
    ],
    description:
      "Premium wireless earbuds with active noise cancellation and spatial audio.",
    brand: "Apple",
    rating: 4.8,
    reviews: 4567,
    inStock: true,
    stock: 78,
    sku: "APL-ARP-PRO",
    weight: "5.4g (each)",
    color: "White",
    colors: ["White"],
    batteryLife: "6 hours (30 with case)",
    features: [
      "Active Noise Cancellation",
      "Spatial Audio",
      "MagSafe Charging",
    ],
    waterResistant: "IPX4",
    tags: ["wireless", "noise-canceling", "premium", "spatial-audio"],
    shipping: {
      free: true,
      estimatedDays: "1-2",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 35,
    name: "Winter Puffer Jacket",
    category: "Fashion",
    subcategory: "Men's Clothing",
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544966503-7cc5ac882d5e?w=400",
    images: [
      "https://images.unsplash.com/photo-1544966503-7cc5ac882d5e?w=400",
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    ],
    description:
      "Warm winter puffer jacket with down insulation and water-resistant outer shell.",
    brand: "The North Face",
    rating: 4.7,
    reviews: 1234,
    inStock: true,
    stock: 45,
    sku: "TNF-WPJ-DOWN",
    weight: "850g",
    color: "Black",
    colors: ["Black", "Navy", "Gray", "Olive"],
    size: "L",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    material: "Nylon Shell, Down Fill",
    waterResistant: true,
    careInstructions: "Machine wash cold, tumble dry low",
    tags: ["winter", "puffer", "down", "water-resistant"],
    shipping: {
      free: true,
      estimatedDays: "4-6",
      cost: 0,
    },
    returnPolicy: "60 days",
    warranty: "1 year",
  },
  {
    id: 36,
    name: "Wool Sweater",
    category: "Fashion",
    subcategory: "Men's Clothing",
    price: 89.99,
    originalPrice: 129.99,
    discount: 31,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
    images: [
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400",
      "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400",
    ],
    description:
      "Premium merino wool sweater with classic crew neck design and soft texture.",
    brand: "J.Crew",
    rating: 4.6,
    reviews: 987,
    inStock: true,
    stock: 67,
    sku: "JCR-WS-CREW",
    weight: "420g",
    color: "Navy",
    colors: ["Navy", "Gray", "Burgundy", "Forest Green", "Charcoal"],
    size: "M",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    material: "100% Merino Wool",
    careInstructions: "Hand wash cold, lay flat to dry",
    tags: ["wool", "sweater", "crew-neck", "merino"],
    shipping: {
      free: false,
      estimatedDays: "5-7",
      cost: 9.99,
    },
    returnPolicy: "60 days",
    warranty: "6 months",
  },
  {
    id: 37,
    name: "Maxi Dress",
    category: "Fashion",
    subcategory: "Women's Clothing",
    price: 94.99,
    originalPrice: 139.99,
    discount: 32,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
    images: [
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400",
    ],
    description:
      "Elegant flowing maxi dress perfect for special occasions and evening events.",
    brand: "Free People",
    rating: 4.5,
    reviews: 1567,
    inStock: true,
    stock: 34,
    sku: "FP-MD-FLOW",
    weight: "380g",
    color: "Emerald Green",
    colors: ["Emerald Green", "Navy Blue", "Burgundy", "Black"],
    size: "M",
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "100% Polyester",
    length: "Maxi Length",
    careInstructions: "Hand wash cold, hang dry",
    tags: ["maxi", "elegant", "evening", "flowing"],
    shipping: {
      free: false,
      estimatedDays: "4-6",
      cost: 8.99,
    },
    returnPolicy: "30 days",
    warranty: "3 months",
  },
  {
    id: 38,
    name: "Blazer Jacket",
    category: "Fashion",
    subcategory: "Women's Clothing",
    price: 119.99,
    originalPrice: 159.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
    images: [
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
    ],
    description:
      "Professional tailored blazer perfect for business meetings and formal occasions.",
    brand: "Ann Taylor",
    rating: 4.7,
    reviews: 876,
    inStock: true,
    stock: 28,
    sku: "AT-BJ-TAIL",
    weight: "540g",
    color: "Black",
    colors: ["Black", "Navy", "Gray", "Camel"],
    size: "M",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    material: "Polyester Blend",
    fit: "Tailored",
    careInstructions: "Dry clean recommended",
    tags: ["blazer", "professional", "tailored", "business"],
    shipping: {
      free: true,
      estimatedDays: "3-5",
      cost: 0,
    },
    returnPolicy: "60 days",
    warranty: "6 months",
  },
  {
    id: 39,
    name: "Leather Boots",
    category: "Fashion",
    subcategory: "Footwear",
    price: 189.99,
    originalPrice: 249.99,
    discount: 24,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544966503-7cc5ac882d5e?w=400",
    images: [
      "https://images.unsplash.com/photo-1544966503-7cc5ac882d5e?w=400",
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400",
    ],
    description:
      "Genuine leather ankle boots with comfortable cushioned sole and classic design.",
    brand: "Dr. Martens",
    rating: 4.8,
    reviews: 2345,
    inStock: true,
    stock: 56,
    sku: "DM-LB-ANKLE",
    weight: "680g",
    color: "Black",
    colors: ["Black", "Brown", "Cherry Red"],
    size: "8",
    sizes: ["6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10", "11"],
    material: "Genuine Leather",
    sole: "Air-Cushioned Sole",
    bootHeight: "Ankle",
    tags: ["leather", "boots", "ankle", "comfortable"],
    shipping: {
      free: true,
      estimatedDays: "3-5",
      cost: 0,
    },
    returnPolicy: "60 days",
    warranty: "1 year",
  },
  {
    id: 40,
    name: "Canvas Tote Bag",
    category: "Fashion",
    subcategory: "Accessories",
    price: 29.99,
    originalPrice: 44.99,
    discount: 33,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
      "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=400",
    ],
    description:
      "Eco-friendly canvas tote bag perfect for shopping and everyday use.",
    brand: "Baggu",
    rating: 4.4,
    reviews: 1876,
    inStock: true,
    stock: 234,
    sku: "BAG-CTB-ECO",
    weight: "180g",
    dimensions: "38 x 33 x 10 cm",
    color: "Natural",
    colors: ["Natural", "Black", "Navy", "Olive", "Terracotta"],
    material: "100% Cotton Canvas",
    capacity: "25L",
    features: ["Reinforced Handles", "Internal Pocket"],
    tags: ["canvas", "tote", "eco-friendly", "shopping"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 4.99,
    },
    returnPolicy: "30 days",
    warranty: "6 months",
  },
  {
    id: 41,
    name: "Queen Size Mattress",
    category: "Home & Garden",
    subcategory: "Bedroom",
    price: 599.99,
    originalPrice: 799.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
      "https://images.unsplash.com/photo-1631049421450-348fcb5da3e6?w=400",
    ],
    description:
      "Memory foam queen mattress with cooling gel layer and medium-firm support.",
    brand: "Casper",
    rating: 4.6,
    reviews: 3456,
    inStock: true,
    stock: 23,
    sku: "CAS-QM-MEM",
    weight: "34kg",
    dimensions: "203 x 153 x 25 cm",
    mattressSize: "Queen",
    mattressSizes: ["Twin", "Full", "Queen", "King", "California King"],
    firmness: "Medium-Firm",
    material: "Memory Foam, Cooling Gel",
    thickness: "25cm",
    tags: ["memory-foam", "cooling", "queen", "medium-firm"],
    shipping: {
      free: true,
      estimatedDays: "7-14",
      cost: 0,
    },
    returnPolicy: "100 nights trial",
    warranty: "10 years",
  },
  {
    id: 42,
    name: "Decorative Throw Pillow Set",
    category: "Home & Garden",
    subcategory: "Home Decor",
    price: 39.99,
    originalPrice: 59.99,
    discount: 33,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
    ],
    description:
      "Set of 4 decorative throw pillows with geometric patterns and soft velvet covers.",
    brand: "West Elm",
    rating: 4.5,
    reviews: 987,
    inStock: true,
    stock: 89,
    sku: "WE-TPS-GEO",
    weight: "1.2kg",
    dimensions: "45 x 45 cm (each)",
    color: "Multi-Color",
    colors: ["Multi-Color", "Blue Tones", "Earth Tones", "Neutral"],
    material: "Velvet Cover, Polyester Fill",
    pattern: "Geometric",
    setSize: "4 pillows",
    tags: ["throw-pillows", "decorative", "geometric", "velvet"],
    shipping: {
      free: false,
      estimatedDays: "5-7",
      cost: 12.99,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 43,
    name: "Indoor Plant Collection",
    category: "Home & Garden",
    subcategory: "Plants",
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    images: [
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400",
    ],
    description:
      "Collection of 5 low-maintenance indoor plants perfect for beginners.",
    brand: "The Sill",
    rating: 4.7,
    reviews: 1234,
    inStock: true,
    stock: 45,
    sku: "SILL-IPC-5",
    plantTypes: [
      "Snake Plant",
      "Pothos",
      "ZZ Plant",
      "Spider Plant",
      "Peace Lily",
    ],
    potSize: "4-6 inches",
    lightRequirement: "Low to Medium",
    waterRequirement: "Weekly",
    petFriendly: "Mixed (some pet-safe)",
    tags: ["indoor-plants", "low-maintenance", "beginner", "collection"],
    shipping: {
      free: true,
      estimatedDays: "5-10",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "Plant health guarantee",
  },
  {
    id: 44,
    name: "Kitchen Knife Set",
    category: "Home & Garden",
    subcategory: "Kitchen",
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544737151-6e4b03a7c9b6?w=400",
    images: [
      "https://images.unsplash.com/photo-1544737151-6e4b03a7c9b6?w=400",
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400",
    ],
    description:
      "Professional 8-piece kitchen knife set with high-carbon steel blades and wooden block.",
    brand: "Henckels",
    rating: 4.8,
    reviews: 2156,
    inStock: true,
    stock: 34,
    sku: "HEN-KNS-8PC",
    weight: "2.3kg",
    pieces: 8,
    material: "High-Carbon Steel",
    includes: [
      "Chef's Knife",
      "Bread Knife",
      "Utility Knife",
      "Paring Knife",
      "Steak Knives (4)",
      "Wooden Block",
    ],
    dishwasherSafe: false,
    tags: ["kitchen", "knives", "professional", "steel"],
    shipping: {
      free: true,
      estimatedDays: "3-5",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "Lifetime",
  },
  {
    id: 45,
    name: "Tennis Racket",
    category: "Sports & Outdoors",
    subcategory: "Tennis",
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=400",
    images: [
      "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=400",
      "https://images.unsplash.com/photo-1594736797933-d0fa48ac3db2?w=400",
    ],
    description:
      "Professional tennis racket with graphite frame and comfortable grip for all skill levels.",
    brand: "Wilson",
    rating: 4.6,
    reviews: 1567,
    inStock: true,
    stock: 67,
    sku: "WIL-TR-GRAPH",
    weight: "290g",
    headSize: "100 sq in",
    stringPattern: "16x20",
    material: "Graphite",
    gripSize: "4 3/8",
    gripSizes: ["4 1/8", "4 1/4", "4 3/8", "4 1/2", "4 5/8"],
    tags: ["tennis", "racket", "graphite", "professional"],
    shipping: {
      free: false,
      estimatedDays: "4-6",
      cost: 9.99,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 46,
    name: "Basketball",
    category: "Sports & Outdoors",
    subcategory: "Basketball",
    price: 24.99,
    originalPrice: 34.99,
    discount: 29,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400",
    images: [
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    ],
    description:
      "Official size basketball with premium leather construction for indoor and outdoor play.",
    brand: "Spalding",
    rating: 4.7,
    reviews: 3456,
    inStock: true,
    stock: 156,
    sku: "SPA-BB-OFFI",
    weight: "624g",
    size: "Official (Size 7)",
    sizes: ["Youth (Size 5)", "Intermediate (Size 6)", "Official (Size 7)"],
    material: "Premium Leather",
    use: "Indoor/Outdoor",
    circumference: "75-78 cm",
    tags: ["basketball", "official", "leather", "spalding"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 6.99,
    },
    returnPolicy: "30 days",
    warranty: "6 months",
  },
  {
    id: 47,
    name: "Camping Tent 4-Person",
    category: "Sports & Outdoors",
    subcategory: "Camping",
    price: 179.99,
    originalPrice: 229.99,
    discount: 22,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=400",
    images: [
      "https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=400",
      "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400",
    ],
    description:
      "Spacious 4-person camping tent with easy setup, waterproof design, and vestibule.",
    brand: "REI Co-op",
    rating: 4.8,
    reviews: 876,
    inStock: true,
    stock: 23,
    sku: "REI-CT-4P",
    weight: "5.2kg",
    dimensions: "274 x 244 x 137 cm",
    capacity: "4 people",
    capacities: ["2 people", "4 people", "6 people"],
    seasons: "3-season",
    waterproof: "3000mm",
    features: ["Easy Setup", "Vestibule", "Interior Pockets"],
    tags: ["camping", "tent", "4-person", "waterproof"],
    shipping: {
      free: true,
      estimatedDays: "5-7",
      cost: 0,
    },
    returnPolicy: "90 days",
    warranty: "1 year",
  },
  {
    id: 48,
    name: "Sunscreen SPF 50",
    category: "Beauty & Personal Care",
    subcategory: "Sun Care",
    price: 16.99,
    originalPrice: 22.99,
    discount: 26,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
      "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400",
    ],
    description:
      "Broad-spectrum SPF 50 sunscreen with zinc oxide, water-resistant for 80 minutes.",
    brand: "Neutrogena",
    rating: 4.5,
    reviews: 4567,
    inStock: true,
    stock: 234,
    sku: "NEU-SS-SPF50",
    weight: "88ml",
    volume: "3 fl oz",
    spf: "SPF 50",
    ingredients: "Zinc Oxide, Titanium Dioxide",
    waterResistant: "80 minutes",
    broadSpectrum: true,
    tags: ["sunscreen", "spf50", "water-resistant", "broad-spectrum"],
    shipping: {
      free: false,
      estimatedDays: "2-4",
      cost: 4.99,
    },
    returnPolicy: "30 days",
    warranty: "N/A",
  },
  {
    id: 49,
    name: "Hair Dryer",
    category: "Beauty & Personal Care",
    subcategory: "Hair Care",
    price: 69.99,
    originalPrice: 89.99,
    discount: 22,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400",
    images: [
      "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400",
      "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400",
    ],
    description:
      "Professional ionic hair dryer with ceramic technology and multiple heat settings.",
    brand: "Revlon",
    rating: 4.4,
    reviews: 2345,
    inStock: true,
    stock: 89,
    sku: "REV-HD-IONIC",
    weight: "680g",
    color: "Black/Gold",
    colors: ["Black/Gold", "White/Silver", "Pink/Rose Gold"],
    wattage: "1875W",
    heatSettings: 3,
    speedSettings: 2,
    features: ["Ionic Technology", "Ceramic Coating", "Cool Shot Button"],
    tags: ["hair-dryer", "ionic", "ceramic", "professional"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 7.99,
    },
    returnPolicy: "30 days",
    warranty: "2 years",
  },
  {
    id: 50,
    name: "Foundation Makeup",
    category: "Beauty & Personal Care",
    subcategory: "Makeup",
    price: 42.99,
    originalPrice: 52.99,
    discount: 19,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400",
    images: [
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400",
      "https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400",
    ],
    description:
      "Full-coverage liquid foundation with 24-hour wear and natural matte finish.",
    brand: "Fenty Beauty",
    rating: 4.6,
    reviews: 5678,
    inStock: true,
    stock: 156,
    sku: "FB-FM-24HR",
    weight: "32ml",
    volume: "1 fl oz",
    shade: "240 (Medium with warm undertones)",
    shades: ["110", "150", "200", "240", "280", "320", "360", "400", "450"],
    coverage: "Full Coverage",
    finish: "Matte",
    wearTime: "24 hours",
    tags: ["foundation", "full-coverage", "matte", "long-wear"],
    shipping: {
      free: false,
      estimatedDays: "2-4",
      cost: 5.99,
    },
    returnPolicy: "30 days",
    warranty: "6 months",
  },
  {
    id: 51,
    name: "Fantasy Novel Series",
    category: "Books & Media",
    subcategory: "Fiction",
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
    images: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    ],
    description:
      "Epic fantasy trilogy boxed set with dragons, magic, and adventure.",
    brand: "Tor Books",
    author: "Brandon Sanderson",
    rating: 4.9,
    reviews: 8765,
    inStock: true,
    stock: 89,
    sku: "TOR-FS-TRIL",
    weight: "1.2kg",
    pages: "1200+ (total)",
    language: "English",
    format: "Paperback Set",
    volumes: 3,
    genre: "Epic Fantasy",
    tags: ["fantasy", "trilogy", "dragons", "bestseller"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 6.99,
    },
    returnPolicy: "30 days",
    warranty: "N/A",
  },
  {
    id: 52,
    name: "Cookbook Collection",
    category: "Books & Media",
    subcategory: "Cooking",
    price: 24.99,
    originalPrice: 34.99,
    discount: 29,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
    images: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    ],
    description:
      "Mediterranean cookbook with 150+ healthy recipes and beautiful photography.",
    brand: "Clarkson Potter",
    author: "Yotam Ottolenghi",
    rating: 4.7,
    reviews: 2345,
    inStock: true,
    stock: 67,
    sku: "CP-CC-MED",
    weight: "890g",
    pages: 320,
    language: "English",
    format: "Hardcover",
    cuisine: "Mediterranean",
    recipes: "150+",
    tags: ["cookbook", "mediterranean", "healthy", "photography"],
    shipping: {
      free: false,
      estimatedDays: "4-6",
      cost: 8.99,
    },
    returnPolicy: "30 days",
    warranty: "N/A",
  },
  {
    id: 53,
    name: "Organic Green Tea",
    category: "Food & Beverages",
    subcategory: "Tea",
    price: 18.99,
    originalPrice: 24.99,
    discount: 24,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400",
    images: [
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400",
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400",
    ],
    description:
      "Premium organic green tea blend with jasmine flowers, 50 tea bags.",
    brand: "Celestial Seasonings",
    rating: 4.5,
    reviews: 1876,
    inStock: true,
    stock: 234,
    sku: "CS-GT-JAS",
    weight: "75g",
    quantity: "50 tea bags",
    organic: true,
    caffeine: "Medium",
    flavor: "Jasmine Green Tea",
    flavors: ["Jasmine Green", "Pure Green", "Mint Green", "Lemon Green"],
    tags: ["organic", "green-tea", "jasmine", "tea-bags"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 4.99,
    },
    returnPolicy: "30 days",
    warranty: "N/A",
  },
  {
    id: 54,
    name: "Artisan Chocolate Box",
    category: "Food & Beverages",
    subcategory: "Confectionery",
    price: 34.99,
    originalPrice: 44.99,
    discount: 22,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1511381939415-e44015466834?w=400",
    images: [
      "https://images.unsplash.com/photo-1511381939415-e44015466834?w=400",
      "https://images.unsplash.com/photo-1549508344-e7e4b7aa4e6e?w=400",
    ],
    description:
      "Luxury assorted chocolate box with 24 handcrafted truffles and pralines.",
    brand: "Godiva",
    rating: 4.8,
    reviews: 1234,
    inStock: true,
    stock: 45,
    sku: "GOD-ACB-24",
    weight: "290g",
    pieces: 24,
    chocolateTypes: ["Dark Chocolate", "Milk Chocolate", "White Chocolate"],
    flavors: ["Raspberry", "Caramel", "Hazelnut", "Vanilla", "Coffee"],
    giftBox: true,
    tags: ["chocolate", "luxury", "artisan", "gift-box"],
    shipping: {
      free: false,
      estimatedDays: "2-4",
      cost: 9.99,
    },
    returnPolicy: "14 days",
    warranty: "N/A",
  },
  {
    id: 55,
    name: "Dog Food Premium",
    category: "Pet Supplies",
    subcategory: "Dog Food",
    price: 49.99,
    originalPrice: 64.99,
    discount: 23,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400",
    ],
    description:
      "Premium dry dog food with real chicken as first ingredient, grain-free formula.",
    brand: "Blue Buffalo",
    rating: 4.6,
    reviews: 3456,
    inStock: true,
    stock: 123,
    sku: "BB-DF-CHICK",
    weight: "13.6kg",
    size: "30 lbs",
    sizes: ["5 lbs", "15 lbs", "30 lbs"],
    protein: "Chicken",
    grainFree: true,
    lifeStage: "Adult",
    lifeStages: ["Puppy", "Adult", "Senior"],
    tags: ["dog-food", "premium", "grain-free", "chicken"],
    shipping: {
      free: true,
      estimatedDays: "5-7",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "Satisfaction guarantee",
  },
  {
    id: 56,
    name: "Cat Scratching Post",
    category: "Pet Supplies",
    subcategory: "Cat Furniture",
    price: 39.99,
    originalPrice: 54.99,
    discount: 27,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=400",
    images: [
      "https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=400",
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
    ],
    description:
      "Tall sisal rope scratching post with multiple levels and hanging toys.",
    brand: "SmartCat",
    rating: 4.7,
    reviews: 1567,
    inStock: true,
    stock: 67,
    sku: "SC-CSP-TALL",
    weight: "4.5kg",
    dimensions: "41 x 41 x 81 cm",
    height: "81 cm",
    material: "Sisal Rope, Pressed Wood",
    features: ["Multiple Levels", "Hanging Toys", "Stable Base"],
    color: "Natural",
    tags: ["cat", "scratching-post", "sisal", "furniture"],
    shipping: {
      free: false,
      estimatedDays: "5-7",
      cost: 12.99,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 57,
    name: "Tablet 10-inch",
    category: "Electronics",
    subcategory: "Tablets",
    price: 329.99,
    originalPrice: 399.99,
    discount: 18,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=400",
    ],
    description:
      "10-inch tablet with high-resolution display, long battery life, and stylus support.",
    brand: "Samsung",
    rating: 4.5,
    reviews: 2876,
    inStock: true,
    stock: 45,
    sku: "SAM-TAB-10",
    weight: "503g",
    dimensions: "24.5 x 15.7 x 0.7 cm",
    screenSize: "10.4 inches",
    resolution: "2000 x 1200",
    storage: "64GB",
    storageOptions: ["32GB", "64GB", "128GB"],
    batteryLife: "13 hours",
    features: ["S Pen Support", "WiFi", "Android OS"],
    tags: ["tablet", "android", "stylus", "portable"],
    shipping: {
      free: true,
      estimatedDays: "2-4",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 58,
    name: "Digital Camera",
    category: "Electronics",
    subcategory: "Cameras",
    price: 599.99,
    originalPrice: 749.99,
    discount: 20,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400",
    images: [
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400",
      "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=400",
    ],
    description:
      "Mirrorless digital camera with 24MP sensor, 4K video recording, and WiFi connectivity.",
    brand: "Canon",
    rating: 4.7,
    reviews: 1876,
    inStock: true,
    stock: 23,
    sku: "CAN-DC-M50",
    weight: "387g",
    dimensions: "11.6 x 8.8 x 5.8 cm",
    megapixels: "24.1 MP",
    videoResolution: "4K",
    lensMount: "Canon EF-M",
    features: ["WiFi", "Bluetooth", "Touchscreen LCD"],
    batteryLife: "305 shots",
    tags: ["camera", "mirrorless", "4k", "wifi"],
    shipping: {
      free: true,
      estimatedDays: "3-5",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 59,
    name: "Fitness Tracker",
    category: "Electronics",
    subcategory: "Wearables",
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400",
    images: [
      "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400",
      "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400",
    ],
    description:
      "Advanced fitness tracker with heart rate monitor, GPS, and 7-day battery life.",
    brand: "Fitbit",
    rating: 4.6,
    reviews: 4567,
    inStock: true,
    stock: 89,
    sku: "FIT-FT-CHARGE",
    weight: "29g",
    color: "Black",
    colors: ["Black", "Blue", "Rose Gold", "Lavender"],
    batteryLife: "7 days",
    waterproof: "50m",
    features: [
      "Heart Rate Monitor",
      "GPS",
      "Sleep Tracking",
      "Smartphone Notifications",
    ],
    tags: ["fitness", "tracker", "gps", "heart-rate"],
    shipping: {
      free: true,
      estimatedDays: "2-3",
      cost: 0,
    },
    returnPolicy: "45 days",
    warranty: "1 year",
  },
  {
    id: 60,
    name: "Denim Skirt",
    category: "Fashion",
    subcategory: "Women's Clothing",
    price: 54.99,
    originalPrice: 74.99,
    discount: 27,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
    images: [
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400",
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400",
    ],
    description:
      "Classic A-line denim skirt with button front closure and knee-length design.",
    brand: "Madewell",
    rating: 4.4,
    reviews: 1234,
    inStock: true,
    stock: 78,
    sku: "MW-DS-ALINE",
    weight: "380g",
    color: "Medium Wash",
    colors: ["Light Wash", "Medium Wash", "Dark Wash"],
    size: "M",
    sizes: ["XS", "S", "M", "L", "XL"],
    length: "Knee Length",
    material: "99% Cotton, 1% Elastane",
    careInstructions: "Machine wash cold, tumble dry low",
    tags: ["denim", "skirt", "a-line", "classic"],
    shipping: {
      free: false,
      estimatedDays: "4-6",
      cost: 7.99,
    },
    returnPolicy: "30 days",
    warranty: "6 months",
  },
  {
    id: 61,
    name: "Polo Shirt",
    category: "Fashion",
    subcategory: "Men's Clothing",
    price: 39.99,
    originalPrice: 54.99,
    discount: 27,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
      "https://images.unsplash.com/photo-1583743814966-8936f37f82e2?w=400",
    ],
    description:
      "Classic fit polo shirt made from breathable cotton pique with ribbed collar.",
    brand: "Ralph Lauren",
    rating: 4.6,
    reviews: 3456,
    inStock: true,
    stock: 134,
    sku: "RL-PS-CLASSIC",
    weight: "220g",
    color: "Navy",
    colors: ["White", "Navy", "Black", "Gray", "Green", "Red"],
    size: "L",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    fit: "Classic Fit",
    material: "100% Cotton Pique",
    careInstructions: "Machine wash warm, tumble dry medium",
    tags: ["polo", "classic", "cotton", "casual"],
    shipping: {
      free: false,
      estimatedDays: "3-5",
      cost: 6.99,
    },
    returnPolicy: "60 days",
    warranty: "6 months",
  },
  {
    id: 62,
    name: "Sunglasses",
    category: "Fashion",
    subcategory: "Accessories",
    price: 159.99,
    originalPrice: 199.99,
    discount: 20,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
    images: [
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400",
    ],
    description:
      "Premium polarized sunglasses with UV400 protection and lightweight titanium frame.",
    brand: "Ray-Ban",
    rating: 4.8,
    reviews: 2876,
    inStock: true,
    stock: 67,
    sku: "RB-SG-POLAR",
    weight: "28g",
    color: "Black/Green",
    colors: ["Black/Green", "Brown/Brown", "Silver/Blue", "Gold/Brown"],
    lensWidth: "58mm",
    lensWidths: ["51mm", "55mm", "58mm"],
    material: "Titanium Frame, Polarized Lenses",
    uvProtection: "100% UV400",
    features: ["Polarized", "UV Protection", "Anti-Reflective"],
    tags: ["sunglasses", "polarized", "uv-protection", "titanium"],
    shipping: {
      free: true,
      estimatedDays: "2-4",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "2 years",
  },
  {
    id: 63,
    name: "Area Rug",
    category: "Home & Garden",
    subcategory: "Home Decor",
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
    ],
    description:
      "Modern geometric area rug with soft texture and fade-resistant colors.",
    brand: "nuLOOM",
    rating: 4.5,
    reviews: 1567,
    inStock: true,
    stock: 34,
    sku: "NUL-AR-GEO",
    weight: "3.2kg",
    dimensions: "200 x 300 cm",
    size: "8' x 10'",
    sizes: ["5' x 8'", "8' x 10'", "9' x 12'"],
    pattern: "Geometric",
    material: "Polypropylene",
    backing: "Jute",
    features: ["Fade Resistant", "Easy Clean", "Low Pile"],
    tags: ["area-rug", "geometric", "modern", "fade-resistant"],
    shipping: {
      free: true,
      estimatedDays: "7-10",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 64,
    name: "Stand Mixer",
    category: "Home & Garden",
    subcategory: "Kitchen",
    price: 399.99,
    originalPrice: 499.99,
    discount: 20,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400",
    ],
    description:
      "Professional stand mixer with 6-quart bowl, 10 speeds, and multiple attachments.",
    brand: "KitchenAid",
    rating: 4.9,
    reviews: 5678,
    inStock: true,
    stock: 15,
    sku: "KA-SM-PROF",
    weight: "11.2kg",
    dimensions: "37 x 22 x 35 cm",
    color: "Empire Red",
    colors: ["Empire Red", "Onyx Black", "White", "Silver", "Aqua Sky"],
    capacity: "6 quarts",
    speeds: 10,
    includes: ["Flat Beater", "Dough Hook", "Wire Whip"],
    motor: "575 Watts",
    tags: ["stand-mixer", "professional", "kitchenaid", "baking"],
    shipping: {
      free: true,
      estimatedDays: "5-7",
      cost: 0,
    },
    returnPolicy: "30 days",
    warranty: "1 year",
  },
  {
    id: 65,
    name: "Garden Tool Set",
    category: "Home & Garden",
    subcategory: "Gardening",
    price: 79.99,
    originalPrice: 109.99,
    discount: 27,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    images: [
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400",
    ],
    description:
      "Complete 10-piece garden tool set with ergonomic handles and storage bag.",
    brand: "Fiskars",
    rating: 4.6,
    reviews: 1876,
    inStock: true,
    stock: 56,
    sku: "FIS-GTS-10PC",
    weight: "2.1kg",
    pieces: 10,
    includes: [
      "Trowel",
      "Transplanter",
      "Weeder",
      "Pruner",
      "Hand Rake",
      "Cultivator",
    ],
    material: "Stainless Steel, Ergonomic Handles",
    storage: "Included Storage Bag",
    tags: ["garden", "tools", "ergonomic", "stainless-steel"],
    shipping: {
      free: false,
      estimatedDays: "5-7",
      cost: 11.99,
    },
    returnPolicy: "90 days",
    warranty: "Lifetime",
  },
];



const seedProducts = async () => {
    const count = await Product.countDocuments();
    if (count === 0) {
        console.log('Seeding products...');
        await Product.insertMany(mockProducts);
    }
};


router.get('/', async (req, res) => {
    try {
        await seedProducts(); 
        const products = await Product.find({});
        res.json(products);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

export default router;